trigger:
  branches:
    include:
      - dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: GOVERSION
    value: '1.23.1'
  - name: GOPATH
    value: '$(Pipeline.Workspace)/messageApi'
  - name: GOBIN
    value: '$(GOPATH)/bin'
  - group: development-variables

stages:
  - stage: Test
    displayName: 'Run Tests'
    jobs:
      - job: UnitTests
        steps:
          - task: GoTool@0
            inputs:
              version: $(GOVERSION)
            displayName: 'Install Go'

          - script: |
              go test ./... -v -cover
            displayName: 'Run Tests'

  - stage: Build
    displayName: 'Build Application'
    dependsOn: Test
    condition: succeeded()
    jobs:
      - job: BuildApp
        steps:
          - task: GoTool@0
            inputs:
              version: $(GOVERSION)
            displayName: 'Install Go'

          - script: |
              CGO_ENABLED=0 GOOS=linux GO_ENV=development go build -o app
            displayName: 'Build Application'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
            displayName: 'Archive Build Files'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish Build Artifacts'

