
trigger:
- master

stages:
  - stage: 'BuildTest'
    displayName: 'Build and Test'
    variables:
      GOVERSION:'1.23.1'
      CGO_ENABLED:'0'
      GOOS:'windows'
    jobs:
      - job: BuildTestBackend
      displayName: 'Build and Test Go Backend'
      pool:
        vmImage: windows-latest
      steps:
      - task: GoTool@0
        inputs:
          version: $(GOVERSION)
        displayName: 'Install and select Go version $(GOVERSION)'
      - script: |
          go get -u github.com/jstemmer/go-junit-report 2>&1
          go get -u github.com/axw/gocov/gocov 2>&1
          go get -u github.com/AlekSi/gocov-xml 2>&1


        





- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    



- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'