name: Evrit Messages Api Flow
on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize
    branches:
      - develop
      - main

env:
  MERGE_AND_DEPLOY_DEVELOP: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'develop' }}
  MERGE_AND_DEPLOY_MAIN: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}
  TAG_VERSION: ${GITHUB_SHA::7}

jobs:
  pr_actions_and_deploy:
    name: PR Actions and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Install dependencies
        run: go get -d -v ./...

      - name: Audit
        run: make audit

      - name: Build
        id: build
        run: go build -v main.go

      - name: Authenticate For deploy
        id: auth
        if: (steps.build.outcome == 'success' && (env.MERGE_AND_DEPLOY_DEVELOP == 'true' || env.MERGE_AND_DEPLOY_MAIN == 'true'))
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ECR Login
        id: ecr_login
        if: (steps.auth.outcome == 'success')
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_ADDRESS }}

      - name: Build Docker Image
        id: build_docker_image
        if: (steps.ecr_login.outcome == 'success')
        run: |
          docker build --build-arg VERSION=${{ env.TAG_VERSION }} -t ${{secrets.REPO_NAME}}:${{ env.TAG_VERSION }} .

      - name: Tag Docker Image
        id: tag_docker_image
        if: (steps.build_docker_image.outcome == 'success')
        run: |
          docker tag ${{secrets.REPO_NAME}}:${{ env.TAG_VERSION }} ${{ secrets.ECR_REPO_ADDRESS }}:${{ env.TAG_VERSION }}

      - name: Push Docker Image
        id: push_docker_image
        if: (steps.tag_docker_image.outcome == 'success')
        run: |
          docker push ${{ secrets.ECR_REPO_ADDRESS }}:${{ env.TAG_VERSION }}

      - name: Evaluate TAG_VERSION Variable
        id: evaluate_tag_version
        if: (steps.push_docker_image.outcome == 'success')
        run: echo "TD_STEP_TAG_VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Update Task definition - DEVELOP
        id: update_task_definition_develop
        if: (steps.evaluate_tag_version.outcome == 'success' && env.MERGE_AND_DEPLOY_DEVELOP == 'true')
        run: |
          aws ecs describe-task-definition --task-definition ${{secrets.TASK_DEFINITION_NAME_DEVELOP}} --query taskDefinition > task-definition.json

      - name: Update Task definition - MAIN
        id: update_task_definition_main
        if: (steps.evaluate_tag_version.outcome == 'success' && env.MERGE_AND_DEPLOY_MAIN == 'true')
        run: |
          aws ecs describe-task-definition --task-definition ${{secrets.TASK_DEFINITION_NAME_MAIN}} --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition
        id: render_ecs_td
        if: (steps.evaluate_tag_version.outcome == 'success')
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: messages-api
          image: ${{ secrets.ECR_REPO_ADDRESS }}:${{ env.TD_STEP_TAG_VERSION }}

      - name: Deploy to Amazon ECS - DEVELOP
        id: deploy_to_ecs_develop
        if: (steps.render_ecs_td.outcome == 'success')
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render_ecs_td.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_DEVELOP }}
          cluster: ${{ secrets.ECS_CLUSTER_DEVELOP }}

      - name: Deploy to Amazon ECS - MAIN
        id: deploy_to_ecs_main
        if: (steps.render_ecs_td.outcome == 'success')
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render_ecs_td.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_MAIN }}
          cluster: ${{ secrets.ECS_CLUSTER_MAIN }}
